return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "blade-formatter",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "hadolint",
      "html-lsp",
      "angular-language-server",
      "phpactor",
      "nginx-language-server",
      "php-debug-adapter",
      "phpcs",
      "pretty-php",
      "prettierd",
      "rustywind",
      "shellcheck",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
    },
  },
}
